name: Unipot
version: "1.7"
license: "GPL-2.0-or-later"
date: 2026-08-16
description: |
    Computing with elements of unipotent subgroups of Chevalley groups

authors:
    - name: Sergei Haller
      url: https://www.sergei-haller.de

maintainers:
    - name: Max Horn
      url: https://www.quendi.de/math

GAP: ">=4.7"

www: https://gap-packages.github.io/unipot/
readme: README.md
packageinfo: https://gap-packages.github.io/unipot/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/unipot/releases/download/v1.7/unipot-1.7.tar.gz

abstract: |
    Tools for computing with elements of unipotent subgroups of Chevalley groups.

status: deposited
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    Chevalley, unipotent elements, unipot.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Hal26</span>]   <b class='BibAuthor'>Haller, S.</b>,
     <i class='BibTitle'>Unipot, Computing with elements of unipotent subgroups of Chevalley groups,
             Version 1.7</i>
     (<span class='BibYear'>2026</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/unipot/">https://gap-packages.github.io/unipot/</a></span>.
    </p>
    

bibtex: |
    @misc{ Unipot,
      author =           {Haller, S.},
      title =            {{Unipot},   {Computing   with  elements  of  unipotent
                          subgroups of Chevalley groups}, {V}ersion 1.7},
      month =            {Aug},
      year =             {2026},
      note =             {GAP package},
      howpublished =     {\href         {https://gap-packages.github.io/unipot/}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{unipot/}}},
      keywords =         {Chevalley; unipotent elements; unipot},
      printedkey =       {Hal26}
    }

