#!/bin/sh
#########################################################################
##
#W  make_doc        make UNIPOT Package documentation         Greg Gamble
##
#H  $Id: make_doc,v 2.5 2004/10/21 21:35:08 gc1007 Exp $
##
##  This shell script uses TeX, BibTeX and MakeIndex to  build  the  .dvi
##  PostScript (commented out), PDF (commented out), and  HTML  (provided
##  you have tth and etc/convert.pl) documentation for the UNIPOT Package.
##

GAP_DIR=../../..
#GAP_DIR=/usr/local/lib/GAP/gap4r3

echo "TeXing documentation"

# TeX the manual and build its bibliography
tex manual; bibtex manual

# TeX the manual again to incorporate the ToC ... and build the index
tex manual; $GAP_DIR/doc/manualindex manual

# Finally TeX the manual again to get cross-references right
tex manual

# Create the PostScript version (uncomment next line, if needed)
dvips -D600 -Ppdf manual

# Create the PDF version (uncomment next line, if needed)
ps2pdf manual.ps

# The HTML version of the manual
mkdir -p ../htm
echo "Creating HTML documentation"
./convert.pl -i -c -t -n Unipot . ../htm

#########################################################################
##
#E
